server:
  port: 9031

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
#    password: password
    password: test1234
#    url: jdbc:mysql://localhost:3306/user-service
    url: jdbc:mysql://localhost:3306/eCommerce
#    username: root
    username: eCommerce-db-sys
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
