server:
  port: 9031

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/user
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
