server:
  port: 9001

spring:
  application:
    name: ACCOUNT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/eCommerce
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
